---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP