apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - image: tic-tac-toe:latest
          imagePullPolicy: Always
          name: tic-tac-toe
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
         
